# Generated by Django 4.1.7 on 2023-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', 'add_slug_to_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name', 'last_name'], name='store_custo_first_n_a7e990_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customers',
        ),
    ]
